spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fornecedor
    password: root
    username: root
    driverClassName: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
